###API 0

GET http://localhost:3000/


###API1
GET http://localhost:3000/todos/?status=TO%20DO


###API2
GET http://localhost:3000/todos/2/

###API3
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 5,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}


###API4
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
  "status": "none"
}

###API5
DELETE http://localhost:3000/todos/2/



###API6
GET http://localhost:3000/todos/